# Generated by Django 4.0.4 on 2022-05-28 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('prenom', models.CharField(blank=True, max_length=200, null=True)),
                ('CIN', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, help_text='Adresse email', max_length=200, null=True)),
                ('tel', models.BigIntegerField(blank=True, null=True)),
                ('CNSS', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('langue', models.CharField(blank=True, max_length=200, null=True)),
                ('passwd', models.IntegerField(blank=True, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
