# Generated by Django 4.0.4 on 2022-05-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='passwd',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
