# Generated by Django 4.0.4 on 2022-06-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_employe_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='createAt',
        ),
    ]
