# Generated by Django 4.0.4 on 2022-06-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_competence_conge_diplome'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='Nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conge',
            name='Prenom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
