# Generated by Django 4.0.4 on 2022-06-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_competence_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employe'),
        ),
        migrations.AddField(
            model_name='diplome',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employe'),
        ),
    ]
