from django.template.defaulttags import url
from django.urls import path
from .views import *

urlpatterns =[ path('', Home.as_view(),name="accueil"),
              path('account/cnx/', EmpInscription.as_view(),name="inscription"),
              path('account/cnx/emp/', HomeEmp.as_view(),name="EmpAccount"),
              path('account/cnx/res/', HomeResp.as_view(),name="RespAccount"),
              path('listE/', EmployeList.as_view(),name="listeEmpl"),
              path('listE/DetailE/<int:idEmp>', DetailEmp.as_view(),name="detailEmp"),
              path('listE/DetailE/add/', AjouterEmp.as_view(), name="AddEmp"),
              path('Supp/<int:idE>', DeleteEmployee.as_view(), name="SuppEmp"),
              path('Modifier/<int:id>', UpdateEmploye.as_view(), name="EmpUpD"),
              path('DmdConge/', DmdConge.as_view(), name="CongD"),
              path('DmdConge/AfficherDmdCong', AfficherDemande.as_view(), name="CongAff"),
              path('GestionConge/', CongeAffichage.as_view(), name="congeS"),
              path('GestionConge/Supp/<int:idG>', CongeDelete.as_view(), name="CongeDeleted"),
              path('Comp/', GestionCompetence.as_view(), name="Compt"),
              path('Comp/AfficherCompetence/', ComptAffichage.as_view(), name="comptS"),
              path('Comp/AfficherCompetence/Supp/<int:idC>', CompDelete.as_view(), name="ComptDeleted"),
              path('Comp/AfficherCompetence/Modifier/<int:idC>', UpdateCompetence.as_view(), name="ComptUpdated"),
              path('Diplome/', GestionDiplome.as_view(), name="Diplome"),
              path('Diplome/Afficher/', DiplomeAffichage.as_view(), name="DipAFF"),
              path('Diplome/Afficher/Supp/<int:idD>', DiplomeDelete.as_view(), name="DipDeleted"),
              path('Diplome/Afficher/UpDate/<int:idD>', DiplomeUpdate.as_view(), name="DipUpdated"),
              path('CV/', GestionCV.as_view(), name="CVEmp"),
              path('CV/Afficher/', AfficherCV.as_view(), name="CVAff"),
              path('CV/Afficher/Cv',  CVAffImage.as_view(), name="CVImg"),
              path('FichePaie/',  GestionFiche.as_view(), name="Fiche"),
              path('FichePaie/Afficher/', FicheAffichage.as_view(), name="FicheAff"),
              path('FichePaie/AfficherResp/', FicheAffichageResp.as_view(), name="FicheResp"),
              path('FichePaie/AfficherResp/Supp/<int:idF>',  FicheDelete.as_view(), name="FicheSupp"),
              path('FichePaie/AfficherResp/Update/<int:idF>', FicheUpdate.as_view(), name="FicheUpDated"),
             ]