# Generated by Django 4.0.4 on 2022-05-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_employe_passwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='User',
        ),
        migrations.AddField(
            model_name='employe',
            name='profil',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, help_text='enter your employee email', max_length=200, null=True),
        ),
    ]
