# Generated by Django 4.0.4 on 2022-06-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_employe_user_employe_profil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='login',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
