# Generated by Django 4.0.4 on 2022-06-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_employe_createat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='tel',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
