# Generated by Django 4.0.4 on 2022-06-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_employe_adresse_alter_employe_cin_alter_employe_cnss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='nom',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
